# Generated by Django 2.2.2 on 2019-06-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_auto_20190610_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Abierto'), (2, 'Reabierto'), (3, 'Solucionado'), (4, 'Cerrados'), (5, 'Duplicados')], help_text='If the status was changed, what was it changed to?', null=True, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=3, choices=[(1, '1. Emergencia'), (2, '2. Urgente'), (3, '3. Normal'), (4, '4. Menos Urgente'), (5, '5. Baja Urgencia')], default=3, help_text='1 = Highest Priority, 5 = Low Priority', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Abierto'), (2, 'Reabierto'), (3, 'Solucionado'), (4, 'Cerrados'), (5, 'Duplicados')], default=1, verbose_name='Status'),
        ),
    ]
